In [ ]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf
from IPython.display import Image
from scipy.stats import ttest_ind, ttest_ind_from_stats

In [ ]:
#read in csv file
df = pd.read_csv('pop-density-table.csv',header=6)
df.head()

[run number] turtle-shape  density-people  pct-wearing-masks  [step]  \
0             7       person             250                 75       0   
1             6       person             250                 75       0   
2             2       person             250                 75       0   
3             8       person             250                 75       0   
4             6       person             250                 75       1   

   pct-affected  pct-deaths  
0           4.8         0.0  
1           4.8         0.0  
2           4.8         0.0  
3           4.8         0.0  
4           6.4         0.0

In [ ]:
#create new dataframe that holds just the numbers at the end of the run (t = 60)
df1 = df[(df['[step]'] == 60)]

In [ ]:
#pivot table of population density vs percent affected over full time period
pd.pivot_table(df, index=['density-people'], 
               values = ['pct-affected'], aggfunc = [np.mean])

mean
               pct-affected
density-people             
250               65.839301
500               83.545705
750               88.746230
1000              91.415213

In [ ]:
import scipy.stats as stats

#one-way anova for densities vs pct-affected
affected250 = df[df['density-people'] == 250]['pct-affected']
affected500 = df[df['density-people'] == 500]['pct-affected']
affected750 = df[df['density-people'] == 750]['pct-affected']
affected1000 = df[df['density-people'] == 1000]['pct-affected']
stats.f_oneway(affected250, affected500, affected750, affected1000)

F_onewayResult(statistic=779.3134097555603, pvalue=0.0)

Because the pvalue for our ANOVA analysis is less than our alpha value of 0.05, we can say that there is a statistically significant difference between the percentage of people affected by the virus for population density of 250, 500, 750, 1000.

In [ ]:
#pivot table of population density vs deaths at the end of the run
pd.pivot_table(df1, index=['density-people'], 
               values = ['pct-deaths'], aggfunc = [np.mean])

mean
               pct-deaths
density-people           
250             82.970667
500             89.837333
750             89.889778
1000            90.092000

In [ ]:
#one-way anova for densities vs pct-deaths
deaths250 = df1[df1['density-people'] == 250]['pct-deaths']
deaths500 = df1[df1['density-people'] == 500]['pct-deaths']
deaths750 = df1[df1['density-people'] == 750]['pct-deaths']
deaths1000 = df1[df1['density-people'] == 1000]['pct-deaths']
stats.f_oneway(deaths250, deaths500, deaths750, deaths1000)

F_onewayResult(statistic=226.10216860069022, pvalue=3.054271856172773e-76)

Because the pvalue for our ANOVA analysis is less than our alpha value of 0.05, we can say that there is a statistically significant difference between the percentage of virus related deaths for population density of 250, 500, 750, 1000.